[tool.poetry]
name = "systemd_mcp"
version = "0.1.0"
description = "a FastMCP server exposing  systemd and other linux API/tools"
authors = ["AI Summit <leonardo_salvatore@trimble.com>"]
readme = "README.md"
packages = [{ include = "systemd_mcp" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastmcp = "<3"
paramiko = "*"
ollama = "*"

[tool.poetry.scripts]
systemd_mcp_server = "systemd_mcp.server:main"
systemd_mcp_cli = "systemd_mcp.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
